# Generated by Django 3.2.5 on 2021-08-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('feed_time1', models.TimeField(null=True)),
                ('feed_time2', models.TimeField(null=True)),
                ('feed_time3', models.TimeField(null=True)),
                ('pre_feedtime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TTYDFunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
